"""update areacode table

Revision ID: 44144b8f13ad
Revises: c3385dcf6d5e
Create Date: 2023-03-11 22:02:21.746184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44144b8f13ad'
down_revision = 'c3385dcf6d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_code_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_code_options', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_code_options')
    )
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areacode_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'area_code_table', ['areacode_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('areacode_id')

    op.drop_table('area_code_table')
    # ### end Alembic commands ###
