"""change cascade deletion

Revision ID: 1ce31aa05141
Revises: a783fe0a8b8d
Create Date: 2023-05-07 01:26:50.617302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ce31aa05141"
down_revision = "a783fe0a8b8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("availability_schedule", schema=None) as batch_op:
        batch_op.drop_constraint(
            "availability_schedule_user_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "user_information", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.drop_constraint("permission_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["user_id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("study_preferences", schema=None) as batch_op:
        batch_op.drop_constraint("study_preferences_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "user_information", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("user_information", schema=None) as batch_op:
        batch_op.drop_constraint("user_information_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["user_id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_information", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "user_information_user_id_fkey", "users", ["user_id"], ["user_id"]
        )

    with op.batch_alter_table("study_preferences", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "study_preferences_user_id_fkey", "user_information", ["user_id"], ["id"]
        )

    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "permission_user_id_fkey", "users", ["user_id"], ["user_id"]
        )

    with op.batch_alter_table("availability_schedule", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "availability_schedule_user_id_fkey",
            "user_information",
            ["user_id"],
            ["id"],
        )

    # ### end Alembic commands ###
