"""rename user information image field

Revision ID: 1d3e492e1ce3
Revises: 556b5303b387
Create Date: 2023-04-17 22:48:27.654333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3e492e1ce3'
down_revision = '556b5303b387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
