"""remove password salt field

Revision ID: 556b5303b387
Revises: e99366544da0
Create Date: 2023-04-15 14:28:45.007917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556b5303b387'
down_revision = 'e99366544da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_password_salt_key', type_='unique')
        batch_op.drop_column('password_salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_salt', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_password_salt_key', ['password_salt'])

    # ### end Alembic commands ###
