"""change timezone to nullable=True

Revision ID: 64accb1b7221
Revises: 1d3e492e1ce3
Create Date: 2023-04-18 22:20:05.942844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64accb1b7221'
down_revision = '1d3e492e1ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
