"""change users model

Revision ID: a783fe0a8b8d
Revises: d9aab2cd3c5a
Create Date: 2023-04-29 22:35:11.937981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a783fe0a8b8d"
down_revision = "d9aab2cd3c5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("availability_schedule", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("study_preferences", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("user_information", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_id", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(
            sa.Column("google_user_name", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(
            sa.Column("google_profile_image", sa.String(length=10000), nullable=True)
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=500), nullable=True
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=500), nullable=True
        )
        batch_op.create_unique_constraint(None, ["user_id"])
        batch_op.create_unique_constraint(None, ["google_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=500), nullable=False
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=500), nullable=False
        )
        batch_op.drop_column("google_profile_image")
        batch_op.drop_column("google_user_name")
        batch_op.drop_column("google_id")

    with op.batch_alter_table("user_information", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("study_preferences", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("availability_schedule", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
