"""change registration table

Revision ID: c3385dcf6d5e
Revises: 
Create Date: 2023-03-11 21:44:15.183152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3385dcf6d5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_method', sa.String(length=500), nullable=False))
        batch_op.create_unique_constraint(None, ['verification_method'])
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['signup_id'])
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('isRegister')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('isRegister', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('signup_id')

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('verification_method')

    # ### end Alembic commands ###
