"""fixing the name for columns in study preferences table

Revision ID: c53bbf2b2c58
Revises: b67546f05446
Create Date: 2023-04-23 18:26:28.950847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c53bbf2b2c58'
down_revision = 'b67546f05446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_env_preferences', sa.Enum('Quiet study areas', 'Group study areas', 'Library', 'Coffee shop', 'Home', 'Outdoors', 'Study room', 'Computer Lab', 'Classroom', 'Open space', 'Private space', 'No preference', name='list_study_env'), nullable=False))
        batch_op.add_column(sa.Column('communication_preferences', sa.Enum('Facebook', 'Twitter', 'Instagram', 'LinkedIn', 'Snapchat', 'TikTok', 'WhatsApp', 'WeChat', 'Skype', 'Slack', 'Discord', 'Reddit', 'Pinterest', 'Tumblr', 'YouTube', 'Vimeo', 'Twitch', 'Clubhouse', 'Zoom', 'Microsoft Teams', name='list_social_media'), nullable=False))
        batch_op.drop_column('study_env_prefereces')
        batch_op.drop_column('communication_prefereces')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('communication_prefereces', postgresql.ENUM('Facebook', 'Twitter', 'Instagram', 'LinkedIn', 'Snapchat', 'TikTok', 'WhatsApp', 'WeChat', 'Skype', 'Slack', 'Discord', 'Reddit', 'Pinterest', 'Tumblr', 'YouTube', 'Vimeo', 'Twitch', 'Clubhouse', 'Zoom', 'Microsoft Teams', name='list_social_media'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('study_env_prefereces', postgresql.ENUM('Quiet study areas', 'Group study areas', 'Library', 'Coffee shop', 'Home', 'Outdoors', 'Study room', 'Computer Lab', 'Classroom', 'Open space', 'Private space', 'No preference', name='list_study_env'), autoincrement=False, nullable=False))
        batch_op.drop_column('communication_preferences')
        batch_op.drop_column('study_env_preferences')

    # ### end Alembic commands ###
