"""new migration

Revision ID: e99366544da0
Revises: 64743d652f5b
Create Date: 2023-04-14 23:16:56.719286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99366544da0'
down_revision = '64743d652f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduation_date', sa.Date(), nullable=False))
        batch_op.drop_column('graduation_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduation_day', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('graduation_date')

    # ### end Alembic commands ###
